spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/step2?characterEncoding=utf8
    username: admin
    password: admin123
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE